const { chromium } = require('./node_modules/@playwright/test');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  const APP_URL = 'https://www.staging-buzzworld-v1.iidm.com';
  const EMAIL = 'defaultuser@enterpi.com';
  const PASSWORD = 'Enspirit@625';
  await page.goto(`${APP_URL}/quote_for_parts`);
  await page.waitForURL('**/Login**', { timeout: 30000 });
  await page.fill('input[name="Email"], input[type="email"]', EMAIL).catch(() => {});
  await page.fill('input[name="Password"], input[type="password"]', PASSWORD).catch(() => {});
  await page.click('button:has-text("Sign In")');
  await page.waitForURL('**/quote_for_parts', { timeout: 60000 });
  await page.waitForTimeout(5000);
  await page.click('text=Repairs');
  await page.waitForSelector('text=Create RMA', { timeout: 30000 });
  await page.click('text=Create RMA');
  await page.waitForSelector('h3:has-text("Create RMA")', { timeout: 30000 });
  await page.locator('div').filter({ hasText: /^Search By Company Name$/ }).nth(2).click();
  await page.waitForTimeout(500);
  await page.fill('input#async-select-example', 'chump03').catch(() => {});
  await page.waitForSelector('#react-select-2-option-0', { timeout: 20000 });
  await page.click('#react-select-2-option-0');
  await page.waitForTimeout(2000);
  await page.fill('input#react-select-4-input', '');
  await page.waitForSelector('div.react-select__menu', { timeout: 20000 });
  await page.locator('div.react-select__option', { hasText: 'Ajay Reddy' }).first().click().catch(async () => {
    await page.locator('div.react-select__option').first().click();
  });
  await page.click('button:has-text("Create")');
  await page.waitForURL(/\/repair-request\/[A-Za-z0-9-]+/, { timeout: 30000 });
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(3000);
  await page.click('text=Add Items');
  await page.waitForSelector('input[name="checkbox0"]', { timeout: 15000 });
  await page.check('input[name="checkbox0"]');
  await page.check('input[name="checkbox1"]');
  await page.check('input[name="checkbox2"]');
  await page.check('input[name="checkbox3"]');
  await page.click('button:has-text("Add Selected 4 Parts")');
  await page.waitForLoadState('networkidle');
  await page.waitForSelector('button:has-text("Add items to quote")', { timeout: 15000 });
  await page.click('button:has-text("Add items to quote")');
  await page.click('button:has-text("Accept")');
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(2000);
  const text = await page.locator('body').innerText();
  console.log('BODY TEXT START');
  console.log(text.slice(0, 8000));
  console.log('BODY TEXT END');
  const buttons = await page.evaluate(() => Array.from(document.querySelectorAll('button')).map(b => ({ text: b.innerText.trim(), disabled: b.disabled })));
  console.log('BUTTONS', JSON.stringify(buttons, null, 2));
  await page.screenshot({ path: 'inspect_quote_buttons2.png', fullPage: true });
  console.log('screenshot saved inspect_quote_buttons2.png');
  await browser.close();
})();
